version: '3.9'

services:
  communebackend:
    build:
      context: .
      args:
        - '-version'
      dockerfile: Dockerfile
    image: communebackend
    container_name: communebackend
    ports:
      - "8080:8080"
    volumes:
      - ./:/src
    expose:
      - "8080"