version: '3.9'

services:
  communebackend:
    build:
      context: .
      args:
        - '-version'
      dockerfile: Dockerfile
    image: communebackend
    container_name: communebackend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/src
    expose:
      - "8080"

  db:
    image: mongo:4.4.4
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    expose:
      - "27017"
